# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Email-Folder-IMAP
version:      1.02
version_from: lib/Email/Folder/IMAP.pm
installdirs:  site
requires:
    Email::Folder::Reader:         
    Email::FolderType::Net:        
    Net::IMAP::Simple:             
    Test::More:                    0.47
    URI::imap:                     

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
